<?php
/**
 * This class was automatically generated by GraphQL Schema generator
 */

namespace GraphAppBundle;

use GraphAppBundle\Mutation\MutationType;
use GraphAppBundle\Query\QueryType;
use Youshido\GraphQL\Config\Schema\SchemaConfig;
use Youshido\GraphQL\Schema\AbstractSchema;

class Schema extends AbstractSchema
{
    public function build(SchemaConfig $config)
    {
        $config
            ->setQuery(new QueryType())
            ->setMutation(new MutationType());
    }
}